apps/devs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name="register"),
    path('login',views.login, name="login")
]

apps/orgs/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.index,name="register"),
	path('login',views.login,name="login")
]

devsondeck/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('devs/',include('apps.devs.urls',namespace="devs")),
    path('orgs/',include('apps.orgs.urls',namespace="orgs"))
]

apps/devs/models.py
from django.db import models

# Create your models here.

apps/orgs/models.py
from django.db import models

# Create your models here.

apps/devs/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.
def index(req):
    return render(req,'devs/register.html')

def login(req):
    return render(req,'devs/login.html')

apps/orgs/views.py
from django.shortcuts import render, HttpResponse

# Create your views here.

def index(req):
	return render(req,"orgs/register.html")

def login(req):
	return render(req,"orgs/login.html")
	

apps/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'components/navbar.html' %}
{% block content %}

{% endblock %}
  </body>
</html>

apps/templates/components/navbar.html
<header>
  <nav class="navbar navbar-light bg-light justify-content-between">
    <div>
      <h1>DevsOnDeck</h1>
    </div>
    <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="#">Dev Login</a></li>
        <li class="nav-item"><a class="nav-link" href="#">Org Login</a></li>
    </ul>
  </nav>
</header>

apps/templates/devs/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container">
  <h1>Welcome Back, Developer!</h1>
  <h3>Let's Connect You to a Job</h3>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group inline-form">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email" placeholder="email">
    </div>
    <div class="form-group inline-form">
      <label for="password">
        Password
      </label>
      <input type="password" name="password" class="form-control" placeholder="password">
    </div>
      <button type="submit" class="btn btn-primary">Log In</button>
  </form>
</div>

{% endblock %}

apps/templates/devs/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<!-- Form For Developer to Sign Up -->

<main class="container">
  <div class="dev-sign-up">
  <h1>Developer Sign Up</h1>
  <form action="#" method="post">
      {% csrf_token %}
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="first_name">First Name</label>
          <input type="text" class="form-control" id="first_name" placeholder="First Name">
        </div>
        <div class="form-group col-md-6">
          <label for="last_name">Last Name</label>
          <input type="text" class="form-control" id="last_name" placeholder="Last Name">
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail4">Email</label>
        <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
      </div>
      <div class="form-group">
        <label for="inputAddress">Address</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
      </div>
      <div class="form-group">
        <label for="inputAddress2">Address 2</label>
        <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <select id="inputState" class="form-control">
          <option value="AL">Alabama</option>
          <option value="AK">Alaska</option>
          <option value="AZ">Arizona</option>
          <option value="AR">Arkansas</option>
          <option value="CA">California</option>
          <option value="CO">Colorado</option>
          <option value="CT">Connecticut</option>
          <option value="DE">Delaware</option>
          <option value="DC">District Of Columbia</option>
          <option value="FL">Florida</option>
          <option value="GA">Georgia</option>
          <option value="HI">Hawaii</option>
          <option value="ID">Idaho</option>
          <option value="IL">Illinois</option>
          <option value="IN">Indiana</option>
          <option value="IA">Iowa</option>
          <option value="KS">Kansas</option>
          <option value="KY">Kentucky</option>
          <option value="LA">Louisiana</option>
          <option value="ME">Maine</option>
          <option value="MD">Maryland</option>
          <option value="MA">Massachusetts</option>
          <option value="MI">Michigan</option>
          <option value="MN">Minnesota</option>
          <option value="MS">Mississippi</option>
          <option value="MO">Missouri</option>
          <option value="MT">Montana</option>
          <option value="NE">Nebraska</option>
          <option value="NV">Nevada</option>
          <option value="NH">New Hampshire</option>
          <option value="NJ">New Jersey</option>
          <option value="NM">New Mexico</option>
          <option value="NY">New York</option>
          <option value="NC">North Carolina</option>
          <option value="ND">North Dakota</option>
          <option value="OH">Ohio</option>
          <option value="OK">Oklahoma</option>
          <option value="OR">Oregon</option>
          <option value="PA">Pennsylvania</option>
          <option value="PR">Puerto Rico</option>
          <option value="RI">Rhode Island</option>
          <option value="SC">South Carolina</option>
          <option value="SD">South Dakota</option>
          <option value="TN">Tennessee</option>
          <option value="TX">Texas</option>
          <option value="UT">Utah</option>
          <option value="VT">Vermont</option>
          <option value="VA">Virginia</option>
          <option value="WA">Washington</option>
          <option value="WV">West Virginia</option>
          <option value="WI">Wisconsin</option>
          <option value="WY">Wyoming</option>
        </select>
      </div>
      <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" placeholder="password" class="form-control">
  </div>
  <div class="form-group">
    <label for="password">Confirm Password</label>
    <input type="password" name="c_password" id="c_password" placeholder="password" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
  <p><a href="{% url 'orgs:register' %}">Need to register as an organization?</a></p>
</main>
<!----------------->

{% endblock %}

apps/templates/orgs/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container">
  <h1>Welcome Back</h1>
  <h3>Let's Find Some Candidates!</h3>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group inline-form">
      <label for="email">Email</label>
      <input type="email" class="form-control" name="email" placeholder="email">
    </div>
    <div class="form-group inline-form">
      <label for="password">
        Password
      </label>
      <input type="password" name="password" class="form-control" placeholder="password">
    </div>
      <button type="submit" class="btn btn-primary">Log In</button>
  </form>
</div>

{% endblock %}

apps/templates/orgs/register.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}

<!-- Form For Organization to Sign Up -->

<main class="container">
  <div class="dev-sign-up">
  <h1>Oranization Sign Up</h1>
  <form action="#" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="org_name">Organzation Name</label>
        <input type="text" name="org_name" class="form-control" id="org_name">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="first_name">First Name</label>
          <input type="text" class="form-control" id="first_name" placeholder="First Name">
        </div>
        <div class="form-group col-md-6">
          <label for="last_name">Last Name</label>
          <input type="text" class="form-control" id="last_name" placeholder="Last Name">
        </div>
      </div>
      <div class="form-group">
        <label for="inputEmail4">Contact Email</label>
        <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
      </div>
      <div class="form-group">
        <label for="inputAddress">Org Address</label>
        <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
      </div>
      <div class="form-group">
        <label for="inputAddress2">Address 2</label>
        <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
      </div>
      <div class="form-row">
        <div class="form-group col-md-6">
          <label for="inputCity">City</label>
          <input type="text" class="form-control" id="inputCity">
        </div>
        <div class="form-group col-md-4">
          <label for="inputState">State</label>
          <select id="inputState" class="form-control">
          <option value="AL">Alabama</option>
          <option value="AK">Alaska</option>
          <option value="AZ">Arizona</option>
          <option value="AR">Arkansas</option>
          <option value="CA">California</option>
          <option value="CO">Colorado</option>
          <option value="CT">Connecticut</option>
          <option value="DE">Delaware</option>
          <option value="DC">District Of Columbia</option>
          <option value="FL">Florida</option>
          <option value="GA">Georgia</option>
          <option value="HI">Hawaii</option>
          <option value="ID">Idaho</option>
          <option value="IL">Illinois</option>
          <option value="IN">Indiana</option>
          <option value="IA">Iowa</option>
          <option value="KS">Kansas</option>
          <option value="KY">Kentucky</option>
          <option value="LA">Louisiana</option>
          <option value="ME">Maine</option>
          <option value="MD">Maryland</option>
          <option value="MA">Massachusetts</option>
          <option value="MI">Michigan</option>
          <option value="MN">Minnesota</option>
          <option value="MS">Mississippi</option>
          <option value="MO">Missouri</option>
          <option value="MT">Montana</option>
          <option value="NE">Nebraska</option>
          <option value="NV">Nevada</option>
          <option value="NH">New Hampshire</option>
          <option value="NJ">New Jersey</option>
          <option value="NM">New Mexico</option>
          <option value="NY">New York</option>
          <option value="NC">North Carolina</option>
          <option value="ND">North Dakota</option>
          <option value="OH">Ohio</option>
          <option value="OK">Oklahoma</option>
          <option value="OR">Oregon</option>
          <option value="PA">Pennsylvania</option>
          <option value="PR">Puerto Rico</option>
          <option value="RI">Rhode Island</option>
          <option value="SC">South Carolina</option>
          <option value="SD">South Dakota</option>
          <option value="TN">Tennessee</option>
          <option value="TX">Texas</option>
          <option value="UT">Utah</option>
          <option value="VT">Vermont</option>
          <option value="VA">Virginia</option>
          <option value="WA">Washington</option>
          <option value="WV">West Virginia</option>
          <option value="WI">Wisconsin</option>
          <option value="WY">Wyoming</option>
        </select>
      </div>
      <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" placeholder="password" class="form-control">
  </div>
  <div class="form-group">
    <label for="password">Confirm Password</label>
    <input type="password" name="c_password" id="c_password" placeholder="password" class="form-control">
  </div>
  <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
</main>
<!----------------->

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'components/navbar.html' %}
{% block content %}

{% endblock %}
  </body>
</html>

templates/components/navbar.html
<div class="top-bar">
  <nav>
    <div class="left logo">
      <h1>DivsOnDeck</h1>
    </div>
    <div class="right">
      <ul>
        <li><a href="#">Dev Login</a></li>
        <li><a href="#">Org Login</a></li>
      </ul>
    </div>
  </nav>
</div>